name: zara_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
   - family: 'Gabarito'
     fonts: 
      - asset: assets/fonts/Gabarito-Regular.ttf
        weight: 400

      - asset: assets/fonts/Gabarito-Medium.ttf
        weight: 500

      - asset: assets/fonts/Gabarito-SemiBold.ttf
        weight: 600

      - asset: assets/fonts/Gabarito-Bold.ttf
        weight: 700

 
   - family: CircularStd
     fonts:
        - asset: assets/fonts/circular-std-medium-500.ttf
          weight: 500
        
        
        
        
        
        
        
        
      

    

